Repository TerraMA2/terrama2, pull requests merged in 2018-02, with the labels that each got.

#1466 log collected date after each file
  src/terrama2/core/utility/ProcessLogger.hpp
  src/terrama2/services/collector/core/Service.cpp
Labels: bug

#1467 trim email targets, fix line break errors
  src/terrama2/services/alert/core/JSonUtils.cpp
Labels: bug

#1469 Fixing analysis exportation
  webapp/core/Exportation.js
  webapp/sockets/Exportation.js
Labels: bug

#1470 Validating system version and SRIDs
  .gitignore
  webapp/controllers/configuration/SRIDValidator.js
  webapp/core/DataManager.js
  webapp/core/facade/tcp-manager/TcpService.js
  webapp/locales/en_US.json
  webapp/locales/es_ES.json
  webapp/locales/pt_BR.json
  webapp/package-lock.json
  webapp/public/javascripts/angular/advanced.html
  webapp/public/javascripts/angular/alerts/controllers/alert-register-update.js
  webapp/public/javascripts/angular/analysis/controllers/register-update.js
  webapp/public/javascripts/angular/data-series/components/storager.js
  webapp/public/javascripts/angular/data-series/directives.js
  webapp/public/javascripts/angular/data-series/registration.js
  webapp/public/javascripts/angular/services/service.js
  webapp/public/javascripts/angular/table/table.js
  webapp/public/javascripts/angular/table/templates/table.html
  webapp/public/javascripts/angular/wizard.html
  webapp/routes/configuration/SRIDValidator.js
  webmonitor/package-lock.json
Labels: enhancement, new feature

#1471 Fixing webmonitor data update bug
  webmonitor/public/javascripts/TerraMA2WebMonitor.js
Labels: bug

#1472 versioning terrama 4.0.3
  DEPENDENCIES
  LINUX.md
  README.md
  build/cmake/CMakeLists.txt
  build/cmake/modules/FindVMime.cmake
  helper/indice_manual.html
  helper/introduction.html
  packages/debian-package/deb-gtest.sh
  packages/debian-package/deb-helper.sh
  packages/debian-package/deb-terrama2.sh
  packages/debian-package/deb-vmime.sh
  packages/dmg-package/dmg-terrama2.sh
  packages/install.sh
  packages/uninstall.sh
  webapp/config/sample_instances/default.json
  webapp/locales/en_US.json
  webapp/locales/es_ES.json
  webapp/locales/pt_BR.json
  webapp/package.json
  webcomponents/package.json
  webmonitor/locales/en.json
  webmonitor/locales/es.json
  webmonitor/locales/pt.json
  webmonitor/package.json
Labels: enhancement

#1473 View table for raster data with timezone
  src/terrama2/services/view/core/data-access/Geoserver.cpp
  src/terrama2/services/view/core/data-access/Geoserver.hpp
Labels: bug

#1474 Fixing status ball bug
  src/terrama2/core/network/TcpManager.cpp
  webapp/public/javascripts/angular/status/status.js
Labels: bug

#1476 versioning vmime and doc packages
  .gitignore
  build/cmake/terrama2_view_core/CMakeLists.txt
  packages/debian-package/deb-helper.sh
  packages/debian-package/deb-vmime.sh
Labels: enhancement

#1477 Don't send start signal to deactivated items / Fixing bugs with automatic schedule
  webapp/core/TcpManager.js
  webapp/core/facade/tcp-manager/ProcessFinished.js
  webapp/core/facade/tcp-manager/TcpService.js
Labels: bug

#1478 1480 view without style for static grid
  src/terrama2/services/view/core/data-access/Geoserver.cpp
  webapp/core/data-model/View.js
  webapp/public/javascripts/angular/views/components/style.js
  webapp/public/javascripts/angular/views/templates/style.html
  webapp/views/configuration/view.html
Labels: enhancement

#1479 Showing image in the webmonitor
  webmonitor/public/javascripts/TerraMA2WebMonitor.js
Labels: new feature

#1480 Execution date from automatic schedule
  src/terrama2/core/network/TcpManager.cpp
  src/terrama2/core/utility/Service.cpp
  src/terrama2/services/analysis/core/Service.cpp
Labels: bug, enhancement

#1481 fix script path
  build/cmake/CMakeLists.txt
  scripts/check-translation-files.py
  scripts/check-translations.py
  webapp/bin/www
Labels: bug

#1482 move update database script to share/terrama2/scripts
  build/cmake/CMakeLists.txt
  share/terrama2/scripts/update_database.py
Labels: bug
