Repository TerraMA2/terrama2, pull requests merged in 2018-07, with the labels that each got.

#1578 Minor improvements
  Changelog.md
  docker/package/Dockerfile
  docker/package/docker.md
  docker/package/entrypoint.sh
  scripts/check-translation-files.py
  scripts/check-translations.py
  webapp/locales/pt_BR.json
Labels: bug, enhancement

#1579 Analysis dcp alert
  Changelog.md
  src/terrama2/impl/DataStoragerDCPPostGIS.cpp
  src/terrama2/impl/DataStoragerDCPPostGIS.hpp
  src/terrama2/services/alert/core/AlertExecutor.cpp
  src/terrama2/services/view/core/data-access/Geoserver.cpp
  webapp/locales/en_US.json
  webapp/locales/es_ES.json
  webapp/locales/pt_BR.json
  webapp/public/javascripts/angular/analysis/controllers/register-update.js
  webapp/public/javascripts/angular/interpolator/templates/wizard.html
  webapp/views/configuration/interpolator.html
Labels: bug

#1580 fix minutes unit in interpolation valid interval
  webapp/public/javascripts/angular/interpolator/templates/inter-parameter.html
Labels: bug

#1581 versioning 4.0.7
  LINUX.md
  build/cmake/CMakeLists.txt
  build/cmake/modules/FindVMime.cmake
  helper/indice_manual.html
  helper/introduction.html
  packages/debian-package/deb-gtest.sh
  packages/debian-package/deb-helper.sh
  packages/debian-package/deb-terrama2.sh
  packages/debian-package/deb-vmime.sh
  webapp/config/sample_instances/default.json
  webapp/locales/en_US.json
  webapp/locales/es_ES.json
  webapp/locales/pt_BR.json
  webapp/package.json
  webcomponents/package.json
  webmonitor/locales/en.json
  webmonitor/locales/es.json
  webmonitor/locales/pt.json
  webmonitor/package.json
Labels: enhancement

#1585 B4.0.6
  Changelog.md
  src/terrama2/services/collector/core/IntersectionOperation.cpp
Labels: bug

#1586 Fix style for vegetation fire, satelite name typo
  Changelog.md
  webapp/public/json_styles/vegetation_fire.json
Labels: bug

#1588 Active project property
  Changelog.md
  build/cmake/CMakeLists.txt
  share/terrama2/scripts/bd_update/4.0-1_4.0-2.sql
  share/terrama2/scripts/parse-http-server-html.py
  share/terrama2/scripts/update_database.py
  src/terrama2/core/Shared.hpp
  src/terrama2/core/data-model/DataManager.cpp
  src/terrama2/core/data-model/DataManager.hpp
  src/terrama2/core/data-model/Project.hpp
  src/terrama2/core/utility/JSonUtils.cpp
  src/terrama2/core/utility/JSonUtils.hpp
  src/terrama2/core/utility/Service.cpp
  webapp/bin/www
  webapp/controllers/configuration/Project.js
  webapp/core/DataManager.js
  webapp/core/Utils.js
  webapp/core/data-model/Project.js
  webapp/core/data-model/index.js
  webapp/core/facade/Project.js
  webapp/models/Project.js
  webapp/views/configuration/project.html
Labels: new feature

#1562 Wind animation first version
  webapp/core/DataManager.js
  webapp/core/data-model/RegisteredView.js
  webapp/public/json_styles/animated_wind_style.json
  webcomponents/javascripts/src/components/MapDisplay.TerraMA2WebComponents.js
  webmonitor/public/javascripts/components/AnimatedLayer.js
  webmonitor/public/javascripts/components/Layers.js
  webmonitor/views/index.html
Labels: new feature

#1589 Translate comments to english, minor improve to docker
  docker/dev/clang_update-alternative.sh
  src/examples/analysis/AnalysisRiscoFogo.cpp
Labels: enhancement

#1591 Fix view permission on webmonitor (temporary)
  webmonitor/controllers/LoginController.js
  webmonitor/gruntfile.js
  webmonitor/package-lock.json
  webmonitor/package.json
  webmonitor/public/javascripts/TerraMA2WebMonitor.js
  webmonitor/public/javascripts/components/Login.js
  webmonitor/public/javascripts/components/State.js
  webmonitor/public/javascripts/components/Utils.js
  webmonitor/sockets/ViewsHandler.js
Labels: bug
