Repository TerraMA2/terrama2, pull requests merged in 2018-06, with the labels that each got.

#1574 Adding template for pull requests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new feature

#1575 Pull request and issues template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new feature

#1576 Fix Webmonitor feature box
  webmonitor/public/javascripts/TerraMA2WebMonitor.js
Labels: bug

#1577 Fix interpolator time unit
  webapp/public/javascripts/angular/interpolator/controllers/interpolator-register-update.js
  webapp/public/javascripts/angular/interpolator/templates/inter-parameter.html
Labels: enhancement
