Repository TerraMA2/terrama2, pull requests merged in 2018-12, with the labels that each got.

#1629 Correction of ocurrence importations from CVS files
  src/terrama2/impl/DataAccessorCSV.cpp
Labels: bug

#1628 WIP: Customize support of WRF files with Temporal Mask handling and minor fixes
  src/terrama2/core/data-access/DataAccessor.cpp
  src/terrama2/core/data-access/DataAccessor.hpp
  src/terrama2/core/data-access/DataRetriever.cpp
  src/terrama2/core/data-access/DataRetriever.hpp
  src/terrama2/core/utility/Utils.cpp
  src/terrama2/core/utility/Utils.hpp
  src/terrama2/impl/DataAccessorFile.cpp
  src/terrama2/impl/DataAccessorFile.hpp
  src/terrama2/impl/DataAccessorGeometricObjectOGR.cpp
  src/terrama2/impl/DataAccessorGeometricObjectOGR.hpp
  src/terrama2/impl/DataAccessorGrADS.cpp
  src/terrama2/impl/DataAccessorGrADS.hpp
  src/terrama2/impl/DataAccessorJsonCemaden.cpp
  src/terrama2/impl/DataAccessorJsonCemaden.hpp
  src/terrama2/impl/DataAccessorPostGIS.cpp
  src/terrama2/impl/DataAccessorPostGIS.hpp
  src/terrama2/impl/DataRetrieverFTP.cpp
  src/terrama2/impl/DataRetrieverFTP.hpp
  src/terrama2/impl/DataRetrieverHTTP.cpp
  src/terrama2/impl/DataRetrieverHTTP.hpp
  src/terrama2/impl/DataRetrieverStaticHTTP.cpp
  src/terrama2/impl/DataRetrieverStaticHTTP.hpp
  src/terrama2/impl/DataStoragerTiff.cpp
  src/terrama2/services/analysis/core/occurrence/zonal/Operator.cpp
  src/terrama2/services/view/core/Utils.cpp
  src/terrama2/services/view/core/Utils.hpp
  src/terrama2/services/view/core/data-access/Geoserver.cpp
  src/terrama2/services/view/core/data-access/Geoserver.hpp
  webapp/core/facade/Analysis.js
  webapp/public/javascripts/angular/services/registration.js
Labels: bug, enhancement

#1630 Include CSV delimiter on semantics Occurrence CSV
  src/terrama2/impl/DataAccessorCSV.cpp
  src/terrama2/services/collector/core/Service.cpp
  webapp/public/javascripts/angular/data-series/components/csvFormat.js
  webapp/public/javascripts/angular/data-series/registration.js
  webapp/public/javascripts/angular/data-series/templates/csvFormat.html
  webapp/public/javascripts/angular/wizard.html
Labels: enhancement

#1632 Updating import/export icons.
  webapp/public/javascripts/angular/table/templates/table.html
Labels: enhancement
