Repository TerraMA2/terrama2, pull requests merged in 2018-03, with the labels that each got.

#1484 fix concurrent access dataset in raster filtering
  src/terrama2/impl/DataAccessorFile.cpp
  src/terrama2/impl/DataAccessorFile.hpp
  src/unittest/collector/IntRasterTs.cpp
Labels: bug

#1485 fix concurrent access dataset in raster filtering cc4ab06
  src/terrama2/impl/DataAccessorFile.cpp
  src/terrama2/impl/DataAccessorFile.hpp
  src/unittest/collector/IntRasterTs.cpp
Labels: bug

#1487 code review
  src/terrama2/core/network/TcpManager.cpp
  src/terrama2/core/network/TcpManager.hpp
  src/terrama2/services/collector/core/IntersectionOperation.cpp
Labels: enhancement

#1488 send webappid on terminate signal
  webapp/core/TcpManager.js
Labels: bug

#1490 Alert internal error
  src/terrama2/core/utility/Utils.cpp
  src/terrama2/core/utility/Utils.hpp
  src/terrama2/services/alert/core/AlertExecutor.cpp
  src/terrama2/services/alert/core/AlertExecutor.hpp
  src/terrama2/services/alert/core/Report.cpp
  src/terrama2/services/alert/core/Report.hpp
  src/terrama2/services/alert/core/Utils.cpp
  src/terrama2/services/alert/core/Utils.hpp
  src/terrama2/services/view/core/data-access/Geoserver.cpp
Labels: bug

#1491 improve alert comparison attribute,
  src/terrama2/core/data-model/Risk.hpp
  src/terrama2/services/alert/core/AlertExecutor.cpp
Labels: enhancement

#1493 fix last commit,
  src/terrama2/services/alert/core/AlertExecutor.cpp
Labels: enhancement

#1492 B4.0.3
  src/terrama2/core/data-model/Risk.hpp
  src/terrama2/core/utility/Utils.cpp
  src/terrama2/core/utility/Utils.hpp
  src/terrama2/services/alert/core/AlertExecutor.cpp
  src/terrama2/services/alert/core/AlertExecutor.hpp
  src/terrama2/services/alert/core/Report.cpp
  src/terrama2/services/alert/core/Report.hpp
  src/terrama2/services/alert/core/Utils.cpp
  src/terrama2/services/alert/core/Utils.hpp
  src/terrama2/services/view/core/data-access/Geoserver.cpp
Labels: enhancement

#1495 1485 dataseries input output attributes
  share/terrama2/semantics/dcp-inpe.json
  share/terrama2/semantics/geo-obj-ogr.json
  share/terrama2/semantics/occurrence-inpe.json
  src/examples/core/AccessLastOccurrenceFromPostGis.cpp
  src/examples/data/OccurrenceWFP.hpp
  src/examples/view/CreateViewDcp.cpp
  src/terrama2/core/data-access/DataAccessor.cpp
  src/terrama2/core/data-access/DataAccessor.hpp
  src/terrama2/impl/DataAccessorDcpInpe.cpp
  src/terrama2/impl/DataAccessorOccurrenceWfp.cpp
  src/terrama2/impl/DataAccessorWildFireEvent.cpp
  src/terrama2/impl/DataStoragerTable.cpp
  src/terrama2/impl/DataStoragerTable.hpp
  webapp/public/javascripts/angular/data-series/registration.js
Labels: bug, enhancement

#1496 check if analysis output raster config is valid,
  src/terrama2/services/analysis/core/GridContext.cpp
Labels: bug

#1498 Fixing pcd bug
  webapp/public/javascripts/angular/data-series/registration.js
Labels: bug

#1499 Status selector in the lists
  webapp/controllers/api/Alert.js
  webapp/controllers/api/Analysis.js
  webapp/controllers/api/DataProvider.js
  webapp/controllers/api/DataSeries.js
  webapp/controllers/api/View.js
  webapp/core/DataManager.js
  webapp/core/facade/Alert.js
  webapp/core/facade/Analysis.js
  webapp/core/facade/DataProvider.js
  webapp/core/facade/View.js
  webapp/public/javascripts/angular/alerts/controllers/alert-list.js
  webapp/public/javascripts/angular/analysis/controllers/list.js
  webapp/public/javascripts/angular/data-provider/controllers/list.js
  webapp/public/javascripts/angular/data-series/data-series.js
  webapp/public/javascripts/angular/table/table.js
  webapp/public/javascripts/angular/table/templates/table.html
  webapp/public/javascripts/angular/views/controllers/view-list.js
  webapp/public/stylesheets/terrama2.css
  webapp/routes/api/Alert.js
  webapp/routes/api/Analysis.js
  webapp/routes/api/DataProvider.js
  webapp/routes/api/DataSeries.js
  webapp/routes/api/View.js
  webapp/routes/configuration/Analysis.js
  webapp/views/configuration/alerts.html
  webapp/views/configuration/analysis_list.html
  webapp/views/configuration/dynamicDataSeries.html
  webapp/views/configuration/providers.html
  webapp/views/configuration/staticData.html
  webapp/views/configuration/views.html
Labels: new feature

#1500 Fixing DCP bug
  webapp/core/DataManager.js
  webapp/public/javascripts/angular/data-series/components/storager.js
Labels: bug

#1501 Analysis webmonitor table
  webmonitor/controllers/GetAttributesTableController.js
  webmonitor/package-lock.json
  webmonitor/public/javascripts/components/AttributesTable.js
  webmonitor/public/javascripts/components/Capabilities.js
  webmonitor/public/javascripts/components/Slider.js
Labels: new feature

#1502 versioning 4.0.4
  LINUX.md
  README.md
  build/cmake/CMakeLists.txt
  build/cmake/modules/FindVMime.cmake
  helper/indice_manual.html
  helper/introduction.html
  packages/debian-package/deb-gtest.sh
  packages/debian-package/deb-helper.sh
  packages/debian-package/deb-terrama2.sh
  packages/debian-package/deb-vmime.sh
  webapp/config/sample_instances/default.json
  webapp/locales/en_US.json
  webapp/locales/es_ES.json
  webapp/locales/pt_BR.json
  webapp/package-lock.json
  webapp/package.json
  webcomponents/package.json
  webmonitor/locales/en.json
  webmonitor/locales/es.json
  webmonitor/locales/pt.json
  webmonitor/package.json
Labels: enhancement

#1503 code review
  src/terrama2/core/utility/Service.cpp
  src/terrama2/services/view/core/data-access/DataAccess.hpp
  webapp/package-lock.json
Labels: enhancement

#1505 use execution date to generate the interpolation
  src/terrama2/services/interpolator/core/Interpolator.cpp
  src/terrama2/services/interpolator/core/Interpolator.hpp
  src/terrama2/services/interpolator/core/Service.cpp
Labels: enhancement

#1508 fix bug of duplicating dataset
  webapp/core/DataManager.js
  webapp/public/javascripts/angular/data-series/registration.js
Labels: bug

#1506 Dynamic shapefile review
  share/terrama2/semantics/geo-obj-ogr.json
  share/terrama2/semantics/occurrence-inpe.json
  src/terrama2/impl/DataAccessorGeometricObjectOGR.cpp
  src/terrama2/impl/DataAccessorGeometricObjectOGR.hpp
  src/terrama2/impl/DataAccessorWildFireEvent.cpp
  src/terrama2/impl/DataAccessorWildFireEvent.hpp
Labels: bug, enhancement

#1509 Fixing bug with projects with special chars in the name
  webapp/controllers/configuration/Project.js
  webapp/controllers/index.js
  webapp/routes/configuration/Project.js
Labels: bug

#1510 Improving view style
  webapp/public/javascripts/angular/views/components/style.js
  webapp/public/javascripts/angular/views/controllers/view-register-update.js
Labels: enhancement

#1512 Fixing dcps bug
  webapp/public/javascripts/angular/data-series/registration.js
Labels: bug

#1515 node package-lock for webcomponents
  src/terrama2/impl/DataStoragerDCPSingleTable.cpp
  webcomponents/package-lock.json
Labels: bug, enhancement

#1517 B4.0
  src/terrama2/impl/DataAccessorFile.cpp
  src/terrama2/impl/DataStoragerDCPSingleTable.cpp
  webapp/public/javascripts/angular/data-series/components/storager.js
  webapp/public/javascripts/angular/data-series/templates/storager.html
  webcomponents/package-lock.json
Labels: enhancement

#1518 fix sql function to get last values for dcp view
  share/terrama2/scripts/dcp_last_measures.sql
Labels: bug
