Repository TerraMA2/terrama2, pull requests merged in 2018-04, with the labels that each got.

#1519 Fixing and documenting package generation
  README.md
  WINDOWS.md
  build/cmake/modules/FindQuaZip.cmake
  build/cmake/modules/FindVMime.cmake
  build/cmake/terrama2_interpolator_core/CMakeLists.txt
  packages/nsis-package/nsis-terrama2-msvc14.bat
  src/terrama2/services/interpolator/core/Config.hpp
  src/terrama2/services/interpolator/core/DataManager.hpp
  src/terrama2/services/interpolator/core/InterpolatorFactories.h
  src/terrama2/services/interpolator/core/InterpolatorLogger.hpp
  src/terrama2/services/interpolator/core/InterpolatorParams.hpp
  src/terrama2/services/interpolator/core/JSonUtils.hpp
  src/terrama2/services/interpolator/core/Service.hpp
Labels: enhancement

#1521 Interpolation icon and status
  webapp/controllers/api/DataSeries.js
  webapp/public/images/interpolation/grid/grid.png
  webapp/public/images/services/interpolation/interpolation_service.png
  webapp/public/javascripts/angular/data-series/services.js
  webapp/public/javascripts/angular/services/service.js
  webapp/public/javascripts/angular/status/status.js
  webapp/public/javascripts/angular/views/controllers/view-list.js
  webapp/views/configuration/dynamicDataSeries.html
Labels: bug, enhancement

#1520 Fix status when changing service in analysis
  webapp/public/javascripts/angular/status/status.js
Labels: bug

#1522 merge B 4.0.4
  README.md
  WINDOWS.md
  build/cmake/modules/FindQuaZip.cmake
  build/cmake/modules/FindVMime.cmake
  build/cmake/terrama2_interpolator_core/CMakeLists.txt
  packages/nsis-package/nsis-terrama2-msvc14.bat
  share/terrama2/scripts/dcp_last_measures.sql
  src/terrama2/services/interpolator/core/Config.hpp
  src/terrama2/services/interpolator/core/DataManager.hpp
  src/terrama2/services/interpolator/core/InterpolatorFactories.h
  src/terrama2/services/interpolator/core/InterpolatorLogger.hpp
  src/terrama2/services/interpolator/core/InterpolatorParams.hpp
  src/terrama2/services/interpolator/core/JSonUtils.hpp
  src/terrama2/services/interpolator/core/Service.hpp
  webapp/controllers/api/DataSeries.js
  webapp/public/images/interpolation/grid/grid.png
  webapp/public/images/services/interpolation/interpolation_service.png
  webapp/public/javascripts/angular/data-series/services.js
  webapp/public/javascripts/angular/services/service.js
  webapp/public/javascripts/angular/status/status.js
  webapp/public/javascripts/angular/views/controllers/view-list.js
  webapp/views/configuration/dynamicDataSeries.html
Labels: enhancement

#1526 Fix Update Data Series
  webapp/controllers/api/DataSeries.js
Labels: bug

#1528 read data from socket when message greater then packages
  webapp/controllers/configuration/ViewsRetriever.js
  webapp/core/Service.js
Labels: bug

#1531 correct data or copy dataset in attribute name conversion
  src/terrama2/core/data-access/SynchronizedDataSet.hpp
  src/terrama2/impl/DataStoragerTable.cpp
  src/terrama2/impl/DataStoragerTable.hpp
Labels: bug

#1527 versioning 4.0.5
  BRANCHES-AND-TAGS
  BUILD-INSTRUCTIONS
  Changelog.md
  DEPENDENCIES
  LINUX.md
  README
  README.md
  VERSIONING.md
  build/cmake/CMakeLists.txt
  build/cmake/modules/FindVMime.cmake
  faq.md
  helper/indice_manual.html
  helper/introduction.html
  packages/debian-package/deb-gtest.sh
  packages/debian-package/deb-helper.sh
  packages/debian-package/deb-terrama2.sh
  packages/debian-package/deb-vmime.sh
  webapp/config/sample_instances/default.json
  webapp/locales/en_US.json
  webapp/locales/es_ES.json
  webapp/locales/pt_BR.json
  webapp/package-lock.json
  webapp/package.json
  webcomponents/package-lock.json
  webcomponents/package.json
  webmonitor/locales/en.json
  webmonitor/locales/es.json
  webmonitor/locales/pt.json
  webmonitor/package.json
Labels: enhancement

#1524 Count pixels by value
  src/terrama2/core/utility/Utils.cpp
  src/terrama2/services/analysis/core/grid/zonal/Operator.cpp
  src/terrama2/services/analysis/core/grid/zonal/Operator.hpp
  src/terrama2/services/analysis/core/python/PythonBindingGrid.cpp
  webapp/public/javascripts/angular/analysis/data/grid-monitored-operators.json
Labels: enhancement

#1525 Use geometry as filter in mo analysis
  src/terrama2/services/analysis/core/BufferMemory.cpp
  src/terrama2/services/analysis/core/BufferMemory.hpp
  src/terrama2/services/analysis/core/grid/zonal/Utils.hpp
  src/terrama2/services/analysis/core/occurrence/zonal/Operator.cpp
Labels: enhancement

#1529 Operator+
  src/terrama2/core/utility/TimeUtils.cpp
  src/terrama2/services/analysis/core/BaseContext.cpp
  src/terrama2/services/analysis/core/BaseContext.hpp
Labels: enhancement

#1532 update branch b4.0.4
  src/terrama2/core/data-access/SynchronizedDataSet.hpp
  src/terrama2/impl/DataStoragerTable.cpp
  src/terrama2/impl/DataStoragerTable.hpp
  webapp/controllers/api/DataSeries.js
  webapp/controllers/configuration/ViewsRetriever.js
  webapp/core/Service.js
Labels: enhancement

#1533 bugfix
  src/terrama2/impl/DataAccessorPostGIS.cpp
  src/terrama2/services/collector/core/Service.cpp
  webapp/core/TcpManager.js
Labels: bug

#1534 fix interpolator finished signal
  src/terrama2/services/interpolator/core/Service.cpp
Labels: bug

#1539 Use yarn for web dependencies
  scripts/postinst.in
  webapp/package.json
  webapp/yarn.lock
  webcomponents/package.json
  webcomponents/yarn.lock
  webmonitor/package.json
  webmonitor/yarn.lock
Labels: enhancement

#1542 fix reading message size in js
  webapp/core/Service.js
Labels: bug

#1543 update 4.0.4
  src/terrama2/core/network/TcpManager.cpp
  src/terrama2/core/network/TcpManager.hpp
  webapp/core/Service.js
Labels: enhancement

#1546 update changelog
  Changelog.md
Labels: enhancement

#1547 fix projection in intersections operations
  src/terrama2/core/data-access/DataAccessorDcp.cpp
  src/terrama2/services/analysis/core/grid/zonal/Utils.hpp
  src/terrama2/services/analysis/core/grid/zonal/history/Operator.cpp
Labels: bug

#1548 Fix tcp communication
  src/terrama2/core/network/TcpManager.cpp
  webapp/core/Service.js
Labels: bug

#1549 fix tcp messages
  src/terrama2/core/network/TcpManager.cpp
  webapp/core/Service.js
Labels: bug

#1551 Fix warnings and doc
  Changelog.md
  src/examples/archiver/KeepLastData.cpp
  src/examples/core/AccessAndFilterOccurrenceFromPostGis.cpp
  src/examples/core/AccessAndFilterOccurrenceMvfFromLocal.cpp
  src/examples/core/AccessAndFilterOccurrenceMvfFromLocalFolder.cpp
  src/examples/core/AccessAndFilterOccurrenceMvfFromLocalFolderToCSV.cpp
  src/examples/core/AccessAndStoreDCPGenericFromLocal.cpp
  src/examples/core/AccessAndStoreDcpInpeFromLocal.cpp
  src/examples/core/AccessAndStoreGridGeoTifFromLocal.cpp
  src/examples/core/AccessAndStoreGridGrADSFromLocal.cpp
  src/examples/core/AccessAndStoreGridGribFromLocal.cpp
  src/examples/core/AccessAndStoreOccurrenceGenericFromLocal.cpp
  src/examples/core/AccessOccurrenceMvfFromLocal.cpp
  src/examples/core/BitsetPolygon.cpp
  src/examples/core/DataRetrieverFromFTP.cpp
  src/examples/core/DataRetrieverFromHTTP.cpp
  src/examples/core/ProcessLogger.cpp
  src/examples/core/RetrieverFromSindaFTP.cpp
  src/terrama2/core/network/TcpManager.cpp
  src/terrama2/core/utility/Timer.hpp
  src/terrama2/impl/DataAccessorOccurrenceLightning.hpp
  src/terrama2/impl/DataAccessorOccurrenceWfp.hpp
  src/terrama2/impl/DataAccessorStaticGDAL.hpp
  webapp/core/Service.js
Labels: bug, enhancement

#1552 small fixes
  Changelog.md
  scripts/config_pm2.sh.in
  webapp/public/javascripts/angular/analysis/data/utilities.json
Labels: bug
