Repository TerraMA2/terrama2, pull requests merged in 2018-08, with the labels that each got.

#1592 TerraMA2 regex expression
  Changelog.md
  src/terrama2/core/utility/FilterUtils.cpp
  src/terrama2/core/utility/FilterUtils.hpp
  webapp/public/javascripts/angular/data-series/services.js
Labels: new feature

#1593 Doc review
  3rdparty/ThreadPool/COPYING
  3rdparty/ThreadPool/README.md
  3rdparty/ThreadPool/ThreadPool.h
  3rdparty/ThreadPool/example.cpp
  3rdparty/webapp-logger/README.md
  build/cmake/CMakeLists.txt
  src/examples/data/DCPSerramarInpe.hpp
  src/examples/data/Geotiff.hpp
  src/examples/data/OccurrenceWFP.hpp
  src/examples/data/ResultAnalysisPostGis.hpp
  src/examples/data/RiscoFogo.hpp
  src/examples/data/StaticPostGis.hpp
  src/examples/data/ViewGeoserver.hpp
  src/terrama2/core/Typedef.hpp
  src/terrama2/core/data-access/DataAccessorGeometricObject.hpp
  src/terrama2/core/data-access/DataRetriever.hpp
  src/terrama2/core/data-access/SynchronizedDataSet.hpp
  src/terrama2/core/data-access/SynchronizedInterpolator.hpp
  src/terrama2/core/data-model/DataManager.hpp
  src/terrama2/core/network/TcpManager.cpp
  src/terrama2/core/utility/CurlWrapperFtp.hpp
  src/terrama2/core/utility/CurlWrapperHttp.hpp
  src/terrama2/impl/DataAccessorAnalysisPostGIS.hpp
  src/terrama2/impl/DataAccessorOccurrenceCSV.hpp
  src/terrama2/impl/DataRetrieverHTTP.hpp
  src/terrama2/services/alert/core/DataManager.hpp
  src/terrama2/services/analysis/core/OperatorCache.hpp
  src/terrama2/services/analysis/core/Typedef.hpp
  src/terrama2/services/collector/core/DataManager.hpp
Labels: enhancement

#1594 Fix project identifier in collector
  webapp/models/Collector.js
  webapp/models/index.js
Labels: bug, enhancement

#1595 Fix potential security vulnerabilities in WebApp and WebMonitor
  webapp/package-lock.json
  webapp/package.json
  webmonitor/package-lock.json
  webmonitor/package.json
Labels: enhancement

#1596 Fix registered view update uri
  webapp/core/DataManager.js
Labels: bug

#1597 review includes in terrama2 core
  src/terrama2/core/data-access/DataAccessor.cpp
  src/terrama2/core/data-access/DataAccessor.hpp
  src/terrama2/core/data-access/DataAccessorDcp.cpp
  src/terrama2/core/data-access/DataAccessorDcp.hpp
  src/terrama2/core/data-access/DataAccessorGrid.cpp
  src/terrama2/core/data-access/DataAccessorGrid.hpp
  src/terrama2/core/data-access/DataAccessorOccurrence.cpp
  src/terrama2/core/data-access/DataAccessorOccurrence.hpp
  src/terrama2/core/data-access/DataRetriever.cpp
  src/terrama2/core/data-access/DataRetriever.hpp
  src/terrama2/core/data-access/DataSetSeries.hpp
  src/terrama2/core/data-access/DataStorager.cpp
  src/terrama2/core/data-access/DataStorager.hpp
  src/terrama2/core/data-access/DcpSeries.cpp
  src/terrama2/core/data-access/DcpSeries.hpp
  src/terrama2/core/data-access/GridSeries.cpp
  src/terrama2/core/data-access/GridSeries.hpp
  src/terrama2/core/data-access/OccurrenceSeries.cpp
  src/terrama2/core/data-access/OccurrenceSeries.hpp
  src/terrama2/core/data-model/DataManager.cpp
  src/terrama2/core/data-model/DataManager.hpp
  src/terrama2/core/data-model/Risk.cpp
  src/terrama2/core/data-model/Risk.hpp
  src/terrama2/core/interpreter/InterpreterFactory.cpp
  src/terrama2/core/interpreter/InterpreterFactory.hpp
  src/terrama2/core/network/TcpManager.cpp
  src/terrama2/core/network/TcpManager.hpp
  src/terrama2/core/utility/BitsetIntersection.cpp
  src/terrama2/core/utility/BitsetIntersection.hpp
  src/terrama2/core/utility/DataAccessorFactory.cpp
  src/terrama2/core/utility/DataAccessorFactory.hpp
  src/terrama2/core/utility/DataRetrieverFactory.cpp
  src/terrama2/core/utility/DataRetrieverFactory.hpp
  src/terrama2/core/utility/DataSetMapper.cpp
  src/terrama2/core/utility/DataSetMapper.hpp
  src/terrama2/core/utility/DataStoragerFactory.cpp
  src/terrama2/core/utility/DataStoragerFactory.hpp
  src/terrama2/core/utility/GeoUtils.cpp
  src/terrama2/core/utility/GeoUtils.hpp
  src/terrama2/core/utility/JSonUtils.cpp
  src/terrama2/core/utility/JSonUtils.hpp
  src/terrama2/core/utility/Logger.cpp
  src/terrama2/core/utility/Logger.hpp
  src/terrama2/core/utility/ProcessLogger.cpp
  src/terrama2/core/utility/ProcessLogger.hpp
  src/terrama2/core/utility/Service.cpp
  src/terrama2/core/utility/Service.hpp
  src/terrama2/core/utility/ServiceManager.cpp
  src/terrama2/core/utility/ServiceManager.hpp
  src/terrama2/core/utility/StoragerManager.cpp
  src/terrama2/core/utility/StoragerManager.hpp
  src/terrama2/core/utility/TerraMA2Init.cpp
  src/terrama2/core/utility/TimeUtils.cpp
  src/terrama2/core/utility/TimeUtils.hpp
  src/terrama2/core/utility/Timer.cpp
  src/terrama2/core/utility/Timer.hpp
  src/terrama2/core/utility/Unpack.cpp
  src/terrama2/core/utility/Unpack.hpp
  src/terrama2/core/utility/Utils.cpp
  src/terrama2/core/utility/Utils.hpp
Labels: enhancement

#1598 recreate layer when deleted from geoserver
  Changelog.md
  src/terrama2/services/view/core/data-access/Geoserver.cpp
Labels: bug

#1599 update pull request model
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#1603 Fix Webcomponents minification
  webcomponents/gruntfile.js
  webcomponents/package-lock.json
  webcomponents/package.json
Labels: bug

#1604 Fix crash when the system has only one core
  Changelog.md
  build/cmake/terrama2-cpack-options.cmake.in
  src/terrama2/core/utility/Service.cpp
  src/terrama2/services/analysis/core/Service.cpp
Labels: bug, enhancement

#1605 update changelog
  Changelog.md
Labels: enhancement

#1606 update changelog
  Changelog.md
Labels: enhancement

#1608 Versioning 4.0.8
  LINUX.md
  VERSIONING.md
  build/cmake/CMakeLists.txt
  build/cmake/modules/FindVMime.cmake
  helper/Introducao.html
  helper/indice_manual.html
  helper/introduction.html
  packages/debian-package/deb-gtest.sh
  packages/debian-package/deb-helper.sh
  packages/debian-package/deb-terrama2.sh
  webapp/config/sample_instances/default.json
  webapp/locales/en_US.json
  webapp/locales/es_ES.json
  webapp/locales/pt_BR.json
  webapp/package.json
  webcomponents/package.json
  webmonitor/locales/en.json
  webmonitor/locales/es.json
  webmonitor/locales/pt.json
  webmonitor/package.json
Labels: enhancement

#1609 Fix import error when collector is null
  webapp/models/Collector.js
Labels: bug

#1610 Fix circular import member on components AnimatedLayer and Layers (te…
  webmonitor/public/javascripts/components/AnimatedLayer.js
Labels: bug

#1611 Disable swipe button to activate/deactivate projects (temporary)
  webapp/public/javascripts/angular/projects/controllers/list.js
Labels: bug

#1612 merge 4.0.7
  webapp/models/Collector.js
  webapp/public/javascripts/angular/projects/controllers/list.js
  webmonitor/public/javascripts/components/AnimatedLayer.js
Labels: enhancement

#1614 fix updating project data
  src/terrama2/core/data-model/DataManager.cpp
  src/terrama2/core/data-model/DataManager.hpp
Labels: bug

#1613 Wfp update
  Changelog.md
  share/terrama2/semantics/occurrence-inpe.json
  src/terrama2/impl/DataAccessorOccurrenceWfp.cpp
Labels: enhancement
