Repository TerraMA2/terrama2, pull requests merged in 2019-01, with the labels that each got.

#1631 Fix GrADS for local folder and ftp files and minor fixes
  src/terrama2/core/data-access/DataAccessor.cpp
  src/terrama2/core/utility/Service.cpp
  src/terrama2/impl/DataAccessorGrADS.cpp
  src/terrama2/impl/DataAccessorPostGIS.cpp
  src/terrama2/impl/DataRetrieverHTTP.cpp
  src/terrama2/services/analysis/core/python/PythonInterpreter.cpp
  src/terrama2/services/analysis/core/python/PythonInterpreter.hpp
  webapp/bin/www
  webapp/core/Logger.js
  webapp/core/Service.js
  webapp/core/facade/tcp-manager/TcpService.js
  webapp/package.json
  webapp/public/javascripts/angular/data-series/directives.js
  webapp/sockets/ServicePortChecker.js
  webapp/sockets/TcpSocket.js
Labels: bug, enhancement

#1633 Fix occurrence postgis semantics
  share/terrama2/semantics/occurrence-postgis.json
Labels: enhancement

#1634 Validating the path informed.
  webapp/public/javascripts/angular/data-provider/controllers/registration.js
Labels: bug

#1636 Bug fix on DCP CSV Update and minor changes
  webapp/bin/www
  webapp/core/executors/Local.js
  webapp/core/facade/tcp-manager/TcpService.js
  webapp/public/javascripts/angular/advanced.html
  webapp/public/javascripts/angular/data-series/components/csvFieldDetail.js
  webapp/public/javascripts/angular/data-series/components/csvFormat.js
  webapp/public/javascripts/angular/data-series/registration.js
  webapp/public/javascripts/angular/data-series/templates/csvFieldDetail.html
  webapp/public/javascripts/angular/data-series/templates/csvFormat.html
  webapp/public/javascripts/angular/wizard.html
  webapp/public/stylesheets/terrama2.css
Labels: bug

#1637 Error Messages
  src/terrama2/core/data-model/DataManager.cpp
  src/terrama2/impl/DataAccessorCSV.cpp
Labels: enhancement

#1639 Fixing the process id
  webapp/public/javascripts/angular/status/status.js
Labels: bug

#1640 Returning empty value when the collector.id is not found.
  webapp/public/javascripts/angular/status/status.js
Labels: bug

#1642 Set icon information on analysis data series
  src/terrama2/impl/DataAccessorCSV.cpp
  src/terrama2/impl/DataAccessorCSV.hpp
  webapp/public/javascripts/angular/analysis/controllers/register-update.js
  webapp/public/javascripts/angular/data-series/services.js
  webapp/sockets/TcpSocket.js
  webapp/views/configuration/analysis.html
Labels: enhancement

#1644 Fix time unit on combobox for Interpolator
  webapp/public/javascripts/angular/interpolator/controllers/interpolator-register-update.js
Labels: bug

#1645 Listing the paths that was added in defaultFilePathList.
  webapp/core/FileRequest.js
  webapp/public/javascripts/angular/data-provider/controllers/registration.js
  webapp/public/javascripts/angular/data-provider/directives.js
  webapp/views/configuration/provider.html
Labels: bug

#1646 Minor change: Set default values in CSV Data Series
  webapp/public/javascripts/angular/data-series/registration.js
  webapp/public/javascripts/angular/data-series/templates/csvFieldDetail.html
Labels: enhancement

#1649 Add sentinel 2 in template maps - webmonitor
  webmonitor/public/javascripts/TerraMA2WebMonitor.js
Labels: enhancement

#1652 Validating if the path exists.
  build/cmake/terrama2_core/CMakeLists.txt
  build/cmake/terrama2_service/CMakeLists.txt
  webapp/public/javascripts/angular/data-provider/controllers/registration.js
Labels: enhancement
