Repository TerraMA2/terrama2, pull requests merged in 2020-09, with the labels that each got.

#1960 Added services configuration to settings.json
  webapp/package-lock.json
  webapp/seeders/20190501115000-service-instance-collector.js
  webapp/seeders/20190501115100-service-instance-analysis.js
  webapp/seeders/20190501115200-service-instance-view.js
  webapp/seeders/20190501115300-service-instance-alert.js
  webapp/seeders/20190501115400-service-instance-interpolator.js
  webcomponents/package-lock.json
  webmonitor/package-lock.json
Labels: new feature

#1964 Fix grid.history.sum dates
  src/terrama2/services/analysis/core/grid/history/Operator.cpp
Labels: bug

#1965 Fix interpolation dummy value
  src/terrama2/services/analysis/core/utility/JSonUtils.cpp
Labels: bug

#1971 Added 'BDC - CBERS4/WFI' template
  install/terrama2-ubuntu-16-04-config.sh
  webcomponents/javascripts/src/components/LayerExplorer.TerraMA2WebComponents.js
  webmonitor/config/sample_instances/user_conf.json
  webmonitor/public/javascripts/TerraMA2WebMonitor.js
  webmonitor/public/javascripts/components/AttributesTable.js
  webmonitor/public/javascripts/components/GetAttributesTool.js
  webmonitor/public/javascripts/components/LayerToolbox.js
  webmonitor/public/javascripts/components/Layers.js
  webmonitor/public/javascripts/components/Legends.js
Labels: enhancement

#1972 modify dinamic filter in Monitored Object
  webapp/views/configuration/analysis.html
Labels: bug
